//! Vectors for the experimental v0.2 Racik + custom tag wrapper.
//! Generated by the independent Python reference in `simulator/riak_v2.py`.
//! All keys are public, non-secret KAT fixtures; never reuse them for data.

struct Vector {
    name: &'static str,
    key: [u32; 16],
    nonce: [u8; 12],
    aad: &'static [u8],
    plaintext: &'static [u8],
    sealed: &'static [u8],
}

const ZERO_KEY: [u32; 16] = [0; 16];
// Public non-secret KAT fixture; never use this key for real data.
const PUBLIC_TEST_KEY: [u32; 16] = [
    0xdead_beef,
    0xcafe_babe,
    0x1234_5678,
    0x9abc_def0,
    0x0f1e_2d3c,
    0x4b5a_6978,
    0x87c6_9d5e,
    0x30a4_b7c1,
    0x55aa_55aa,
    0xff00_ff00,
    0x0123_4567,
    0x89ab_cdef,
    0xdead_beef,
    0xcafe_babe,
    0x1357_9bdf,
    0x2468_ace0,
];
const STRUCTURED_KEY: [u32; 16] = [
    0x0001_0203,
    0x0405_0607,
    0x0809_0a0b,
    0x0c0d_0e0f,
    0x1011_1213,
    0x1415_1617,
    0x1819_1a1b,
    0x1c1d_1e1f,
    0x2021_2223,
    0x2425_2627,
    0x2829_2a2b,
    0x2c2d_2e2f,
    0x3031_3233,
    0x3435_3637,
    0x3839_3a3b,
    0x3c3d_3e3f,
];

const VECTORS: &[Vector] = &[
    Vector {
        name: "zero/empty",
        key: ZERO_KEY,
        nonce: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
        aad: b"RIAK2C",
        plaintext: b"",
        sealed: &[
            0x61, 0xc5, 0xa6, 0xe4, 0x44, 0xec, 0x2b, 0x5f, 0x98, 0xa5, 0x79, 0x34, 0xa9, 0xc7,
            0x0a, 0xa0,
        ],
    },
    Vector {
        name: "mixed/message",
        key: PUBLIC_TEST_KEY,
        nonce: [0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b],
        aad: b"header-v2",
        plaintext: b"custom RIAK v0.2 message",
        sealed: &[
            0x59, 0x0e, 0x66, 0xbe, 0xd4, 0xb4, 0xc7, 0xf2, 0xaf, 0x11, 0x10, 0x79, 0x07, 0xeb,
            0x64, 0x0d, 0x7a, 0x0b, 0x6e, 0x8f, 0xa6, 0xa8, 0xf1, 0x6a, 0x52, 0x69, 0x86, 0x09,
            0x2e, 0xc5, 0x5c, 0x70, 0xa4, 0xfa, 0x8c, 0x62, 0xce, 0x75, 0x38, 0xdb,
        ],
    },
    Vector {
        name: "structured/33_bytes",
        key: STRUCTURED_KEY,
        nonce: [0xa0, 0xa1, 0xa2, 0xa3, 0xa4, 0xa5, 0xa6, 0xa7, 0xa8, 0xa9, 0xaa, 0xab],
        aad: b"A",
        plaintext: &[
            0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
            23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        ],
        sealed: &[
            0x27, 0xcd, 0xc1, 0xa8, 0xae, 0x81, 0xd5, 0xe4, 0xc4, 0x21, 0x78, 0x5b, 0xfc, 0xbc,
            0x00, 0xa4, 0x3e, 0x5e, 0x16, 0x2e, 0x6e, 0x1c, 0xa6, 0x70, 0x16, 0xec, 0xcb, 0xaa,
            0xff, 0x7a, 0xa9, 0x22, 0xe9, 0x6a, 0xaa, 0x91, 0xd1, 0x6a, 0x49, 0x8f, 0x6f, 0xde,
            0xfc, 0xd6, 0xb9, 0x93, 0x34, 0x42, 0x16,
        ],
    },
];

#[test]
fn match_python_custom_cipher_vectors() {
    for vector in VECTORS {
        let cipher = riak::v2::RiakV2Cipher::from_words(vector.key);
        let sealed = cipher
            .seal(&vector.nonce, vector.aad, vector.plaintext)
            .unwrap();
        assert_eq!(sealed, vector.sealed, "seal mismatch: {}", vector.name);
        assert_eq!(
            cipher.open(&vector.nonce, vector.aad, vector.sealed).unwrap(),
            vector.plaintext,
            "open mismatch: {}",
            vector.name
        );
    }
}
