//! Vectors generated by the independent Python reference in
//! `simulator/riak_v2.py`. Do not edit by hand.
//! All keys are public, non-secret KAT fixtures; never reuse them for data.

#![allow(dead_code)]

struct Vector {
    name: &'static str,
    key: [u32; 16],
    pt: [u32; 4],
    ct: [u32; 4],
}

const ZERO_KEY: [u32; 16] = [0; 16];
const FF_KEY: [u32; 16] = [0xffff_ffff; 16];
const STRUCTURED_KEY: [u32; 16] = [
    0x0001_0203,
    0x0405_0607,
    0x0809_0a0b,
    0x0c0d_0e0f,
    0x1011_1213,
    0x1415_1617,
    0x1819_1a1b,
    0x1c1d_1e1f,
    0x2021_2223,
    0x2425_2627,
    0x2829_2a2b,
    0x2c2d_2e2f,
    0x3031_3233,
    0x3435_3637,
    0x3839_3a3b,
    0x3c3d_3e3f,
];
// Public non-secret KAT fixture; never use this key for real data.
const PUBLIC_TEST_KEY: [u32; 16] = [
    0xdead_beef,
    0xcafe_babe,
    0x1234_5678,
    0x9abc_def0,
    0x0f1e_2d3c,
    0x4b5a_6978,
    0x87c6_9d5e,
    0x30a4_b7c1,
    0x55aa_55aa,
    0xff00_ff00,
    0x0123_4567,
    0x89ab_cdef,
    0xdead_beef,
    0xcafe_babe,
    0x1357_9bdf,
    0x2468_ace0,
];

const ZERO_PT: [u32; 4] = [0, 0, 0, 0];
const STANDARD_PT: [u32; 4] = [0x0123_4567, 0x89ab_cdef, 0xfedc_ba98, 0x7654_3210];
const RANDOM_PT: [u32; 4] = [0x3c4f_9a12, 0xb8d7_e601, 0x5a0c_7f3b, 0x92e1_4d86];

const VECTORS: &[Vector] = &[
    Vector {
        name: "zero_key/zero",
        key: ZERO_KEY,
        pt: ZERO_PT,
        ct: [0xa49d_e39d, 0x51d2_4bf4, 0xe885_3ccd, 0xdd97_971d],
    },
    Vector {
        name: "zero_key/standard",
        key: ZERO_KEY,
        pt: STANDARD_PT,
        ct: [0x292e_f30e, 0xbb3d_c595, 0x6a49_c7ff, 0x5ba3_b63c],
    },
    Vector {
        name: "zero_key/random",
        key: ZERO_KEY,
        pt: RANDOM_PT,
        ct: [0xb7d0_d354, 0x990e_8f10, 0x07d0_d4d6, 0xfeec_0710],
    },
    Vector {
        name: "ff_key/zero",
        key: FF_KEY,
        pt: ZERO_PT,
        ct: [0xc14a_771c, 0xf569_8f5d, 0x2b61_44a1, 0xda51_376b],
    },
    Vector {
        name: "ff_key/standard",
        key: FF_KEY,
        pt: STANDARD_PT,
        ct: [0x33e1_a6e4, 0xa4ee_98dd, 0x3c68_5905, 0x151f_7058],
    },
    Vector {
        name: "ff_key/random",
        key: FF_KEY,
        pt: RANDOM_PT,
        ct: [0x7132_bbdd, 0x44fa_ac6e, 0xcaac_0545, 0x6400_b38f],
    },
    Vector {
        name: "structured_key/zero",
        key: STRUCTURED_KEY,
        pt: ZERO_PT,
        ct: [0x00ae_4ef8, 0xd7b5_6b40, 0xe2e0_c29e, 0x22fb_521a],
    },
    Vector {
        name: "structured_key/standard",
        key: STRUCTURED_KEY,
        pt: STANDARD_PT,
        ct: [0xf566_2712, 0xd088_d75a, 0xcb98_1676, 0xb8e4_327b],
    },
    Vector {
        name: "structured_key/random",
        key: STRUCTURED_KEY,
        pt: RANDOM_PT,
        ct: [0xa7f2_abbb, 0x51ae_42d2, 0xa37f_de7c, 0x487a_3942],
    },
    Vector {
        name: "mixed_key/zero",
        key: PUBLIC_TEST_KEY,
        pt: ZERO_PT,
        ct: [0x41bb_4ccf, 0xdaf7_2043, 0x7a62_5a7a, 0xc1bb_8ba5],
    },
    Vector {
        name: "mixed_key/standard",
        key: PUBLIC_TEST_KEY,
        pt: STANDARD_PT,
        ct: [0x42b1_f455, 0x6fce_e45c, 0xbd38_f04c, 0x22d0_3f9e],
    },
    Vector {
        name: "mixed_key/random",
        key: PUBLIC_TEST_KEY,
        pt: RANDOM_PT,
        ct: [0x6964_58e7, 0x40ee_8f85, 0x0de0_6635, 0xce08_c181],
    },
];

#[test]
fn match_python_v2_vectors() {
    for vector in VECTORS {
        let cipher = riak::v2::RiakV2::from_words(vector.key);
        let mut block = vector.pt;
        cipher.encrypt_block(&mut block);
        assert_eq!(block, vector.ct, "v0.2 encryption mismatch: {}", vector.name);
        cipher.decrypt_block(&mut block);
        assert_eq!(block, vector.pt, "v0.2 decryption mismatch: {}", vector.name);
    }
}
