//! Deterministic Python-reference cross-check fixture for v0.3 wrapper.
//! Generated by `simulator/generate_v3_vectors.py`.

use riak::v3::RiakV3Cipher;

fn decode_hex(token: &str) -> Vec<u8> {
    if token == "-" {
        return Vec::new();
    }
    assert!(token.len() % 2 == 0, "odd-length hex token");
    token
        .as_bytes()
        .chunks(2)
        .map(|pair| {
            let text = std::str::from_utf8(pair).expect("fixture is ASCII");
            u8::from_str_radix(text, 16).expect("fixture contains valid hex")
        })
        .collect()
}

#[test]
fn python_generated_wrapper_cases_match() {
    let fixture = include_str!("data/v3_fuzz_vectors.txt");
    let mut cases = 0usize;
    for (line_number, line) in fixture.lines().enumerate() {
        let fields: Vec<&str> = line.split_whitespace().collect();
        assert_eq!(fields.len(), 5, "bad fixture line {}", line_number + 1);
        let key_bytes = decode_hex(fields[0]);
        let nonce_bytes = decode_hex(fields[1]);
        let aad = decode_hex(fields[2]);
        let plaintext = decode_hex(fields[3]);
        let expected = decode_hex(fields[4]);
        assert_eq!(key_bytes.len(), 64);
        assert_eq!(nonce_bytes.len(), 12);

        let mut key = [0u8; 64];
        key.copy_from_slice(&key_bytes);
        let mut nonce = [0u8; 12];
        nonce.copy_from_slice(&nonce_bytes);
        let cipher = RiakV3Cipher::new(&key);
        let sealed = cipher
            .seal(&nonce, &aad, &plaintext)
            .expect("fixture encryption failed");
        assert_eq!(sealed, expected, "fixture mismatch at case {}", line_number);
        assert_eq!(
            cipher.open(&nonce, &aad, &sealed).expect("fixture open failed"),
            plaintext
        );
        cases += 1;
    }
    assert_eq!(cases, 128);
}
