//! Vectors generated by the independent Python reference in
//! `simulator/riak_v3.py`. Do not edit by hand.
//! All keys are public, non-secret KAT fixtures; never reuse them for data.

#![allow(dead_code)]

struct Vector {
    name: &'static str,
    key: [u32; 16],
    pt: [u32; 4],
    ct: [u32; 4],
}

const ZERO_KEY: [u32; 16] = [0; 16];
const FF_KEY: [u32; 16] = [0xffff_ffff; 16];
const STRUCTURED_KEY: [u32; 16] = [
    0x0001_0203,
    0x0405_0607,
    0x0809_0a0b,
    0x0c0d_0e0f,
    0x1011_1213,
    0x1415_1617,
    0x1819_1a1b,
    0x1c1d_1e1f,
    0x2021_2223,
    0x2425_2627,
    0x2829_2a2b,
    0x2c2d_2e2f,
    0x3031_3233,
    0x3435_3637,
    0x3839_3a3b,
    0x3c3d_3e3f,
];
// Public non-secret KAT fixture; never use this key for real data.
const PUBLIC_TEST_KEY: [u32; 16] = [
    0xdead_beef,
    0xcafe_babe,
    0x1234_5678,
    0x9abc_def0,
    0x0f1e_2d3c,
    0x4b5a_6978,
    0x87c6_9d5e,
    0x30a4_b7c1,
    0x55aa_55aa,
    0xff00_ff00,
    0x0123_4567,
    0x89ab_cdef,
    0xdead_beef,
    0xcafe_babe,
    0x1357_9bdf,
    0x2468_ace0,
];

const ZERO_PT: [u32; 4] = [0, 0, 0, 0];
const STANDARD_PT: [u32; 4] = [0x0123_4567, 0x89ab_cdef, 0xfedc_ba98, 0x7654_3210];
const RANDOM_PT: [u32; 4] = [0x3c4f_9a12, 0xb8d7_e601, 0x5a0c_7f3b, 0x92e1_4d86];

const VECTORS: &[Vector] = &[
    Vector {
        name: "zero_key/zero",
        key: ZERO_KEY,
        pt: ZERO_PT,
        ct: [0x9352_17c4, 0x78b9_9009, 0x4bdf_3051, 0x655b_5891],
    },
    Vector {
        name: "zero_key/standard",
        key: ZERO_KEY,
        pt: STANDARD_PT,
        ct: [0x3929_48f5, 0x6d4a_90a8, 0xc693_ceb2, 0x93bc_31d7],
    },
    Vector {
        name: "zero_key/random",
        key: ZERO_KEY,
        pt: RANDOM_PT,
        ct: [0xaaa3_cbe2, 0x8226_58db, 0x09be_4f7b, 0x0679_6bd4],
    },
    Vector {
        name: "ff_key/zero",
        key: FF_KEY,
        pt: ZERO_PT,
        ct: [0x9fe6_b32d, 0x26f2_822c, 0xa3d6_eb53, 0x8655_1d91],
    },
    Vector {
        name: "ff_key/standard",
        key: FF_KEY,
        pt: STANDARD_PT,
        ct: [0x9de4_d8a1, 0x4b56_ba50, 0x9937_f0d5, 0x8cfb_d42f],
    },
    Vector {
        name: "ff_key/random",
        key: FF_KEY,
        pt: RANDOM_PT,
        ct: [0x4b6e_6019, 0x8df2_7609, 0xdeec_2d73, 0x2a2a_3356],
    },
    Vector {
        name: "structured_key/zero",
        key: STRUCTURED_KEY,
        pt: ZERO_PT,
        ct: [0x5689_6643, 0x75ac_cf81, 0xb720_c0a1, 0x7103_f858],
    },
    Vector {
        name: "structured_key/standard",
        key: STRUCTURED_KEY,
        pt: STANDARD_PT,
        ct: [0xe551_ce14, 0xf51d_b89e, 0x8107_61e1, 0x6c51_7497],
    },
    Vector {
        name: "structured_key/random",
        key: STRUCTURED_KEY,
        pt: RANDOM_PT,
        ct: [0xce7c_7e10, 0xc144_e172, 0x10b4_f0ef, 0xee21_7b1a],
    },
    Vector {
        name: "mixed_key/zero",
        key: PUBLIC_TEST_KEY,
        pt: ZERO_PT,
        ct: [0x901a_5a1f, 0x9462_6166, 0xe5e0_3acc, 0xaf70_81e2],
    },
    Vector {
        name: "mixed_key/standard",
        key: PUBLIC_TEST_KEY,
        pt: STANDARD_PT,
        ct: [0x2499_0781, 0x8d19_2b9e, 0x4d65_bcfe, 0x7dd9_4a50],
    },
    Vector {
        name: "mixed_key/random",
        key: PUBLIC_TEST_KEY,
        pt: RANDOM_PT,
        ct: [0xf572_5980, 0xf01b_99ff, 0x888d_3a06, 0xd04e_224b],
    },
];

#[test]
fn match_python_v3_vectors() {
    for vector in VECTORS {
        let cipher = riak::v3::RiakV3::from_words(vector.key);
        let mut block = vector.pt;
        cipher.encrypt_block(&mut block);
        assert_eq!(block, vector.ct, "v0.3 encryption mismatch: {}", vector.name);
        cipher.decrypt_block(&mut block);
        assert_eq!(block, vector.pt, "v0.3 decryption mismatch: {}", vector.name);
    }
}
